### ISSUE TITLE
Account name case sensitivity

### ISSUE THREAD

**Issue by jtuu** [zxc23/dcss-scoreboard#5]
On some servers my account name is `esc` but on others it is `Esc` (annoying, I know). Looks like regardless of this they are all linked together which is nice.
But one problem I noticed is that on the scoreboard the morgue file URLs all use `Esc` as the account name which causes 404 on links to servers where the account name is `esc`.

Example:
- [`http://dobrazupa.org/morgue/Esc/morgue-Esc-20140823-230051.txt`](http://dobrazupa.org/morgue/Esc/morgue-Esc-20140823-230051.txt) this URL is fine because my account name on CSZO was `Esc`
- [`http://crawl.xtahua.com/crawl/morgue/Esc/morgue-Esc-20161024-164218.txt`](http://crawl.xtahua.com/crawl/morgue/Esc/morgue-Esc-20161024-164218.txt) this URL 404s because my account name on CXC is `esc`

**Comment by alexjurkiewicz** [comment]
Thanks for the report, should be fixed now! You'll need to finish a game to have your player page regenerated.
